[package]
name = "image-watermark"
version = "0.1.0"
authors = ["Chakrit Wichian <service@chakrit.net>"]
edition = "2018"

[dependencies]
image = "^0.23"
imageproc = "^0.21"
rusttype = "^0.9"
unicode-normalization = "^0.1"
